{{- if eq .Values.bundle.source "redhat" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istiod
  namespace: {{ .Values.namespace }}
imagePullSecrets:
  - name: {{ .Values.pullSecret.name }}
{{- end }}
