#!/bin/bash
# Post-install message with next steps

echo ""
echo "============================================"
echo "  Sail Operator Installed Successfully!"
echo "============================================"
echo ""
echo "NEXT STEPS:"
echo ""
echo "1. Deploy your application (e.g., llm-d)"
echo ""
echo "2. After deploying, patch the gateway ServiceAccount:"
echo ""
echo "   export APP_NAMESPACE=llmd-pd"
echo "   kubectl get secret redhat-pull-secret -n istio-system -o yaml | sed \"s/namespace: istio-system/namespace: \${APP_NAMESPACE}/\" | kubectl apply -f -"
echo "   kubectl patch serviceaccount <gateway-sa-name> -n \${APP_NAMESPACE} -p '{\"imagePullSecrets\": [{\"name\": \"redhat-pull-secret\"}]}'"
echo "   kubectl delete pod -n \${APP_NAMESPACE} -l gateway.istio.io/managed=istio.io-gateway-controller"
echo ""
echo "See README.md for full documentation."
echo "============================================"
echo ""
